### ISSUE TITLE
Distinguish SaaS from self-hosted/on-premises software

### ISSUE THREAD

**Issue by nodiscc** [onurakpolat/awesome-analytics#93]
Following the move from awesome-selfhosted (https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2024#issuecomment-722792179) it would be nice to know which software can be run by the user on their own machine, and which software only runs as [SaaS](https://www.gnu.org/philosophy/who-does-that-server-really-serve.html) outside the user's control.

/cc @jtagcat

**Comment by luckydonald** [comment]
What is missing is something to search for selfhostable software, as there is no uniform tag for all of those.
Especially since users are referred here from the selfhosted list [issue](https://github.com/awesome-selfhosted/awesome-selfhosted/issues/2024#issuecomment-766484025), that might be something to consider.

With the PRs and the merged parts already there, there's no way to `ctrl+f` for a `selfhosted` tag. But one can easily jump to the `SaaS` ones, which to see seems to less likely to be a needed feature.

**Comment by onurakpolat** [comment]
Thanks friends!

**Comment by luckydonald** [comment]
@onurakpolat Alright, alright, I'll open an issue for that.
